name: Security Scan with opengrep

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sast_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Ensure pip is up to date
        run: |
          python -m pip install --upgrade pip

      - name: Clone and Install opengrep
        run: |
          git clone https://github.com/opengrep/opengrep.git
          cd opengrep
          pip install . -v
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Verify working directory
        run: |
          pwd
          ls -al

      - name: Verify opengrep Installation
        run: |
          pip list
          which opengrep || echo "opengrep not found in PATH"
          find $HOME/.local/bin -name "opengrep" || echo "opengrep not found in .local/bin"
          pip show opengrep || echo "opengrep not installed via pip"

      - name: Run SAST with opengrep
        run: |
          opengrep scan ./src --output opengrep-report.json || python -m opengrep scan ./src --output opengrep-report.json

      - name: Upload opengrep Report
        uses: actions/upload-artifact@v4
        with:
          name: opengrep-report
          path: opengrep-report.json
