name: Security Scan with OpenGREP

on:
  push:
    branches:
      - dev
  # pull_request:
  #   branches:
  #     - main

jobs:
  opengrep_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install OpenGREP (semgrep)
        run: |
          pip install semgrep
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          semgrep --version

      - name: Verify OpenGrep Installation
        run: |
          which semgrep || echo "OpenGrep (Semgrep) not found"
          semgrep --help

      # - name: Run SAST with OpenGREP
      #   run: |
      #      run: |
      #         if [ -d "rules" ]; then
      #           semgrep scan --sarif-output=phishing_opengrep-report.json -f rules code
      #         else
      #           semgrep scan --sarif --output=phishing_opengrep-report.json --config=auto
      #         fi

      - name: Run SAST with OpenGREP and Generate SARIF Report
        run: |
          if [ -d "rules" ]; then
            semgrep scan --sarif --output=opengrep-results.sarif -f rules code
          else
            semgrep scan --sarif --output=opengrep-results.sarif --config=auto
          fi

      # - name: Upload OpenGREP Report
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: phishing_opengrep-report
      #     path: phishing_opengrep-report.json

      - name: Upload OpenGREP SARIF Report
        uses: actions/upload-artifact@v4
        with:
          name: opengrep-sarif-report
          path: opengrep-results.sarif

      - name: Upload SARIF Report to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: opengrep-results.sarif
