name: Security Scan with OpenGREP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  opengrep_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install OpenGREP (semgrep)
        run: |
          # python -m pip install --upgrade pip
          # pip install git+https://github.com/opengrep/opengrep.git
          pip install semgrep
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          semgrep --version

      - name: Verify OpenGrep Installation
        run: |
          which semgrep || echo "OpenGrep (Semgrep) not found"
          semgrep --help

      - name: Run SAST with OpenGREP
        run: |
          if [ -d "rules" ]; then
            semgrep scan --sarif-output=sarif.json -f rules code
          else
            semgrep scan --sarif --output=sarif.json --config=auto
          fi

      - name: Upload OpenGREP Report
        uses: actions/upload-artifact@v4
        with:
          name: opengrep-report
          path: opengrep-report.json
