name: Security Scan with opengrep

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sast_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install opengrep
        run: |
          pip install opengrep

      - name: Run SAST with opengrep
        run: |
          opengrep scan ./src --output opengrep-report.json

      - name: Upload opengrep Report
        uses: actions/upload-artifact@v4
        with:
          name: opengrep-report
          path: opengrep-report.json
