name: Security Scan with opengrep

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sast_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install opengrep
        run: |
          pip install git+https://github.com/opengrep/opengrep.git
          
      - name: Run SAST with opengrep
        run: |
          # If opengrep is installed as a module, use python -m to run it
          python -m opengrep scan ./src --output opengrep-report.json

      - name: Upload opengrep Report
        uses: actions/upload-artifact@v4
        with:
          name: opengrep-report
          path: opengrep-report.json
