name: Security Scan with opengrep

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sast_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Upgrade pip and Install opengrep
        run: |
          python -m pip install --upgrade pip
          pip install --force-reinstall git+https://github.com/opengrep/opengrep.git
          pip show opengrep  # Verify opengrep is installed
          which opengrep || echo "opengrep not found in PATH"
          echo "User base binary directory:"
          ls -la $(python -m site --user-base)/bin  # Check where it's installed
          echo "Python site-packages:"
          python -m site  # Show Python paths to confirm where modules are being installed

      - name: Run SAST with opengrep
        run: |
          export PATH="$HOME/.local/bin:$PATH"  # Add user base bin to PATH
          opengrep scan ./src --output opengrep-report.json || python -m opengrep scan ./src --output opengrep-report.json

      - name: Upload opengrep Report
        uses: actions/upload-artifact@v4
        with:
          name: opengrep-report
          path: opengrep-report.json
