name: Security Scan with OpenGREP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  opengrep_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install OpenGREP
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/opengrep/opengrep.git

      - name: Verify OpenGREP Installation
        run: |
          pip list | grep opengrep
          python -c "import opengrep; print(opengrep.__version__)"

      - name: Run SAST with OpenGREP
        run: |
          python -m opengrep scan . --output opengrep-report.json

      - name: Upload OpenGREP Report
        uses: actions/upload-artifact@v4
        with:
          name: opengrep-report
          path: opengrep-report.json
